# /opt/tdf-stack/docker-compose.yml
# version: '3.8'

services:
  # --- Service 1: Nginx (The Gateway) ---
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - n8n
      - fastapi

  # --- Service 2: n8n ---
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - N8N_HOST=n8n.srv1163611.hstgr.cloud
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://n8n.srv1163611.hstgr.cloud/
      - GENERIC_TIMEZONE=Asia/Kolkata
    volumes:
      - ./tdf_n8n:/home/node/.n8n
    user: "1000:1000" # Critical for permissions

  # --- Service 3: FastAPI ---
  fastapi:
    build: ./tdf_api
    container_name: my_fastapi
    restart: always
  