version: "3"
services:
  api:
    container_name: tdfapi
    build: tdf_api/.
    env_file:
      - ./.env
    command: "uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"

  chatbot:
    container_name: tdfchatbot
    build: tdf_chatbot/.
    env_file:
      - ./.env
    command: "streamlit run --server.port 8501 app.py"
    ports:
      - "8501:8501"